# https://www.netlify.com/docs/netlify-toml-reference/

[build]
  publish = "netlify"
  command = "./scripts/travis.sh"

[build.environment]
  NODE_VERSION = "lts/*"
  # TODO remove
  TRAVIS_MODE = "netlifyBranch"

[context.deploy-preview.environment]
  # TODO remove
  TRAVIS_MODE = "netlifyPr"
